server:
  port: 8001

spring:
  application:
    name: gateway-server
  profiles:
    include: redis
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.114.69:8848
    gateway:
      routes:
        - id: support-server
          uri: lb://support-server
          predicates:
            - Path=/api/support/**
          filters:
            - StripPrefix=1
#            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - id: travel-server
          uri: lb://travel-server
          predicates:
            - Path=/api/travel/**
          filters:
            - StripPrefix=1
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: user-server
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1



whitelist:
  urls:
    - /api/test
    - /api/auth/token